Method testing
KerronKing/testing-enumerables pull request #2
Opened 2019-09-13 21:16 UTC by KerronKing

2019-09-14 00:56 UTC, bolah2009 requested changes
# Hi @KerronKing    :wave: 

### Awesome Job :muscle: 

Few things before getting a :+1: 
- Add Descriptive readme
  > Remember about descriptive README file.
- Is there a reason why you using a new repo? :thinking: 
  > Use existing repositories for `Tic Tac Toe` and `Enumerables`: add specs and open new Pull Requests.
- Test for both negative and positive cases. See comment below.
  > Use your common sense: test positive and negative scenarios.
- Use `let` to define variables for test cases
- Add PR description

| Current | Preffred |
|:-----:|:-----|
| ![prking](https://user-images.githubusercontent.com/36057474/64901514-2670b280-d692-11e9-8e48-970f6a3998f1.png) | ![update-PR-description-html](https://user-images.githubusercontent.com/36057474/64305800-6e078800-cf88-11e9-82f0-04e13fd6cb8d.gif) |

#### Is there a reason you the only one working on this project? This is a **collaborative** project. :thinking: 

#### Fix this and submit another code review request. :ok_hand: 

#### Feel free to reach me on slack if you having issues implementing these features. :+1: 

Good luck with your next submission. :star2: 

Cheers :confetti_ball: 
[Bola](https://bolabuari.com/)

###### PS: Note that comments tagged as `OPTIONAL` are not part of the minimum requirements to approve this PR

2019-09-14 00:56 UTC, bolah2009 commented on spec/main_spec.rb
> +      expect(arr.my_count).to eql(5)
:thinking: What happens when a block is passed? Or an argument is passed?
Please, let's add edge cases for the test. This test is not yet effective as it passes even like this (Commenting out part of the code). :point_down: 
```ruby
def my_count(&block)
    # result = []
    return size unless block_given?

    # my_each do |elem|
    #   result << elem if block.call(elem) == true
    # end
    # result.size
  end
```

2019-09-14 00:56 UTC, bolah2009 commented on spec/main_spec.rb
> +      expect(arr.my_any? { |x| x > 2 }).to(eql(true))
:thinking: What happens when the block returns false for each value? For example: :point_down: 
```suggestion
      expect(arr.my_any? { |x| x > 2 }).to(eql(true))
      expect(arr.my_any? { |x| x > 5 }).to(eql(false))
```
Please, let's add edge cases for the test. This test is not yet effective as it passes even like this (Commenting out part of the code). :point_down: 
```ruby
  def my_any?(&block)
    counter = 0
    my_each do |elem|
      counter += 1 if block.call(elem) == true
    end
    return true if counter.positive?

    # false
  end
```

2019-09-14 00:56 UTC, bolah2009 commented on spec/main_spec.rb
> +      expect(arr.my_none? { |x| x > 4 }).to(eql(true))
Check comment above on writing both negative and positive cases.

2019-09-14 00:56 UTC, bolah2009 commented on spec/main_spec.rb
> +      arr = [1, 2, 3]
#### `REQUIRED`
Let's use `let` here instead. I can see you use `arr = [1, 2, 3]` in four different places already. You can define this `arr` using `let` helper method after the first `describe` block and use it anywhere else. See example below:

```ruby
RSpec.describe Enumerable do
let(:arr){[1, 2, 3]}

```

Learn more about [`let` here](https://relishapp.com/rspec/rspec-core/v/2-5/docs/helper-methods/let-and-let)

2019-09-14 00:56 UTC, bolah2009 commented on spec/main_spec.rb
> +      expect(arr.my_map { |x| x * 2 }).to(eql(result))
#### `OPTIONAL` 
You can also use `to` without the parenthesis.

```ruby
expect(arr.my_map { |x| x * 2 }).to eql(result)
```

2019-09-16 20:30 UTC, samgaco approved these changes
#### Hi @KerronKing and @MarvellousUbani :high_brightness: 

#### All the requested changes have been met therefore the project is approved :white_check_mark: . You may now merge to the master branch and submit the project completion form :1st_place_medal: 

------------------------------
**[SUGGESTION]** I would suggest improving the readme file, you might check this [template](https://github.com/othneildrew/Best-README-Template) for inspiration or this [course](https://www.udacity.com/course/writing-readmes--ud777). You could try to answer questions that someone going into your repo not familiar with the project would ask himself.

--------------------------------
* ###### STATUS OF THE PROJECT: APPROVED :heavy_check_mark:

2019-09-16 20:30 UTC, samgaco commented on spec/main_spec.rb
> +  end
Block and argument test cases implemented :+1:

2019-09-16 20:30 UTC, samgaco commented on spec/main_spec.rb
> +      expect(arr.my_any? { |x| x > 3 }).to eql(false)
:100:

2019-09-16 20:30 UTC, samgaco commented on spec/main_spec.rb
> +      expect(arr.my_none? { |x| x > 2 }).to eql(false)
:white_check_mark:

2019-09-16 20:39 UTC, merged